import { execSync } from 'node:child_process';
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import pg from 'pg';

/**
 * Playwright global setup. Runs once before the suite.
 *
 * Strict DB-name guard. The suite is allowed to wipe and re-seed exactly
 * one database: `vera_test` on `localhost`. ANY other target (`vera_dev`,
 * `vera_prod`, a remote host) causes this setup to throw before a single
 * row is touched. There is no override flag — running tests against the
 * dev or prod DB is never the right answer.
 *
 * What it does (in order):
 *   1. Resolve DATABASE_URL from env or apps/web/.env.local. If unset,
 *      skip the entire setup (DB-less runs of public-route specs).
 *   2. Verify the connection is to `vera_test` on localhost. Throw
 *      otherwise.
 *   3. Wipe all data tables in FK-safe order.
 *   4. Re-load `tests/fixtures/vera_test.sql` so each suite run starts
 *      from the identical seed.
 *   5. Refresh `LiveJob` so the read path sees the seeded rows.
 *
 * The seed file is generated by `scripts/generate-vera-test-seed.ts` and
 * checked into git. To rebuild it, re-run the generator. To re-provision
 * the DB from scratch, run `scripts/setup-vera-test.sh`.
 */

const ALLOWED_DB = 'vera_test';
const ALLOWED_HOSTS = new Set<string | null>(['127.0.0.1', '::1', null]);
// `null` = local Unix domain socket connection — `inet_server_addr()`
// returns NULL when libpq dials over a socket instead of TCP.

export default async function globalSetup(): Promise<void> {
  const dbUrl = resolveDatabaseUrl();
  if (!dbUrl) {
    // eslint-disable-next-line no-console
    console.warn('[playwright global-setup] DATABASE_URL not found — skipping DB reset');
    return;
  }

  // ─────────────────────────────────────────────────────────────────────
  // Identity probe — strict invariants.
  // ─────────────────────────────────────────────────────────────────────
  const probe = new pg.Client({ connectionString: dbUrl });
  let dbName = '';
  let host: string | null = null;
  try {
    await probe.connect();
    // `host(inet_server_addr())` strips the CIDR mask suffix that
    // `::text` would leave on the address (e.g. "::1/128" → "::1").
    // NULL is returned for Unix-socket connections.
    const res = await probe.query<{ db: string; host: string | null }>(
      `SELECT current_database() AS db, host(inet_server_addr()) AS host`,
    );
    dbName = res.rows[0]?.db ?? '';
    host = res.rows[0]?.host ?? null;
  } finally {
    await probe.end().catch(() => undefined);
  }

  if (dbName !== ALLOWED_DB) {
    throw new Error(
      `[playwright global-setup] Refusing to wipe — current_database() is "${dbName}", expected "${ALLOWED_DB}".\n` +
        `Set DATABASE_URL=postgresql://localhost/${ALLOWED_DB} (or use \`pnpm test:e2e\` which sets it for you).\n` +
        `There is no override flag. The suite is allowed to wipe ${ALLOWED_DB} only.`,
    );
  }
  if (!ALLOWED_HOSTS.has(host)) {
    throw new Error(
      `[playwright global-setup] Refusing to wipe — connection is to "${host}", not localhost.\n` +
        `${ALLOWED_DB} must live on the developer's machine only.`,
    );
  }

  // eslint-disable-next-line no-console
  console.log(
    `[playwright global-setup] target verified: ${ALLOWED_DB} on ${host ?? 'unix-socket'}`,
  );

  // ─────────────────────────────────────────────────────────────────────
  // Wipe + reseed.
  //
  // The seed file at tests/fixtures/vera_test.sql already wraps its own
  // INSERTs in BEGIN/COMMIT and starts with DELETE statements for the
  // same tables, so passing it through `prisma db execute` re-establishes
  // the canonical state in one shot. We also refresh LiveJob after so
  // the materialized view reflects the freshly-inserted RawRooflinkJob
  // rows.
  // ─────────────────────────────────────────────────────────────────────
  const seedPath = resolveSeedPath();
  if (!existsSync(seedPath)) {
    throw new Error(
      `[playwright global-setup] seed file not found at ${seedPath}.\n` +
        `Generate it first: pnpm exec tsx scripts/generate-vera-test-seed.ts`,
    );
  }

  try {
    execSync(
      `pnpm --filter @vera/web exec prisma db execute --schema prisma/schema.prisma --file "${seedPath}"`,
      {
        env: { ...process.env, DATABASE_URL: dbUrl },
        stdio: ['ignore', 'ignore', 'inherit'],
      },
    );
    execSync(
      `pnpm --filter @vera/web exec prisma db execute --schema prisma/schema.prisma --stdin`,
      {
        input: 'REFRESH MATERIALIZED VIEW "LiveJob";',
        env: { ...process.env, DATABASE_URL: dbUrl },
        stdio: ['pipe', 'ignore', 'inherit'],
      },
    );
    // eslint-disable-next-line no-console
    console.log('[playwright global-setup] seed reloaded + LiveJob refreshed');
  } catch (e) {
    // eslint-disable-next-line no-console
    console.error('[playwright global-setup] seed reload failed:', e);
    throw e;
  }
}

function resolveDatabaseUrl(): string | null {
  if (process.env.DATABASE_URL) return stripQuotes(process.env.DATABASE_URL);
  const envPath = join(process.cwd(), 'apps/web/.env.local');
  if (!existsSync(envPath)) return null;
  const env = readFileSync(envPath, 'utf8');
  const m = env.match(/^DATABASE_URL=(.+)$/m);
  return m ? stripQuotes(m[1].trim()) : null;
}

function resolveSeedPath(): string {
  return join(process.cwd(), 'tests/fixtures/vera_test.sql');
}

function stripQuotes(s: string): string {
  return s.replace(/^"(.*)"$/, '$1').replace(/^'(.*)'$/, '$1');
}
